name: standard_searchbar
description: A simple and very customizable search bar widget for Flutter.
version: 2.0.3
repository: https://github.com/ManelRosPuig/StandardSearchBar
license: MIT

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter: